### ISSUE TITLE
Improve CoAP client

### ISSUE THREAD

**Issue by arturkow2000** [fobnail/fobnail#34]
Following problems need to fixed:

- Last CoAP message ID is lost when Fobnail is changing modes (provisioning -> attestation). Also when Fobnail starts always message ID of 1 is used as the first ID. This may result in CoAP server (attester or platform owner) thinking that incoming packet is duplicate and responding with old cached response .
- Some ACK handling code is missing and Fobnail does not send ACK in some circumstances. This results in server retransmitting the same few times.
- Other TODOs/FIXMEs from CoAP code should be fixed.

**Comment by krystian-hebel** [comment]
This issue no longer applies as we've changed the architecture and now Fobnail Token is CoAP server, not client. See https://github.com/fobnail/fobnail/issues/43, https://github.com/fobnail/docs/pull/39 and https://github.com/fobnail/fobnail/pull/48.
